### ISSUE TITLE
Windows - Terminal clears itself when pressing key "k" on the keyboard

### ISSUE THREAD

**Issue by 8UA** [Saadmairaj/tkterminal#11]

**Comment by 8UA** [comment]
nvm, got it to work on a different machine.

**Comment by WaterWalo** [comment]
> nvm, got it to work on a different machine.

Did you find a way to fix it ?

**Comment by 8UA** [comment]
> Did you find a way to fix it ?

No, but trying on another machine `(Python 3.10.2)` did it for me.
