### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by arnav56745** [Saadmairaj/tkterminal#14]
When I use in script, it says `"ModuleNotFoundError: No module named 'tkterminal'"`

**Comment by Moosems** [comment]
Probably a bad install. ModuleNotFoundError's don't happen because of the module

**Comment by arnav56745** [comment]
I did `pip install tkterminal` & `pip3 install tkterminal`

**Comment by arnav56745** [comment]
(When I use in intepreter, it imports successfully)

**Comment by Moosems** [comment]
What python version and computer are you using? It works just fine for me and I've used it plenty without ever having this issue

**Comment by arnav56745** [comment]
Python3.10.9 (ms store) and windows 10

**Comment by Moosems** [comment]
Can you give full stack trace please?

**Comment by arnav56745** [comment]
`Traceback (most recent call last):
  File "USER*/Favorites/Downloads/a1.py", line 1, in <module>
    from tkterminal import *
ModuleNotFoundError: No module named 'tkterminal'`
* USER being my user folder

**Comment by arnav56745** [comment]
I am forced to use `tkterm` because of this.

**Comment by arnav56745** [comment]
Hello?

**Comment by Evernow** [comment]
> Python3.10.9 (ms store) and windows 10

Can you try not installing it from the msstore? I can't reproduce this, seems like an install problem on your end.

**Comment by arnav56745** [comment]
@Evernow yeah, I tried with C:\python311 and it worked
(i updated to py 3.11)

**Comment by Moosems** [comment]
Yeah that's an error from improper  installation.
