### ISSUE TITLE
TypeError: '<=' not supported between instances of 'int' and 'NoneType'

### ISSUE THREAD

**Issue by mrrabyss** [Saadmairaj/tkterminal#15]
When I tried to write /bin/bash or /bin/zsh or sudo su, this error happened

**Comment by Moosems** [comment]
Dude that's a python error, not a tkterminal error 🤦

**Comment by mrrabyss** [comment]
ok

**Comment by lebao3105** [comment]
From README.md:

> Command that requires input.

> The tkterminal is using subprocess python module where the input can only  be passed before running the command and cannot be passed after the command has ran.

So bash, sh, sudo and any other commands that require inputs will not work in TkTerminal

**Comment by mrrabyss** [comment]
thank you
