### ISSUE TITLE
get cwd of the terminal?

### ISSUE THREAD

**Issue by Whirlpool-Programmer** [Saadmairaj/tkterminal#2]
is there any feature to get the cwd of the terminal?
so that you can change the prompt text according to the cwd and make it better..

**Comment by Saadmairaj** [comment]
Hi, thanks for mentioning it but sadly this feature is not quiet there yet, this project is still in beta and I'm not getting enough time to complete it.

**Comment by Saadmairaj** [comment]
Feature added in the first non beta release `v0.1.0`, you can do

```
pip install tkterminal --upgrade
```
