### ISSUE TITLE
make the code wait

### ISSUE THREAD

**Issue by SL-Pirate** [Saadmairaj/tkterminal#4]
Is there any method to make my code wait until the terminal process is completed like the `wait()` function in the subprocess module?

Or is there anyway just to make the terminal widget get destroyed automatically after the terminal process is done?

**Comment by Saadmairaj** [comment]
I don't think I've implemented the wait functionality yet. However, it works like a normal shell which should support the cmd command `sleep 30` and combined use of thread you can achieve something similar

**Comment by SL-Pirate** [comment]
Well actually all I want is just run my app and when the user says run {this} command then pop a terminal in a window and run the specific command and when it's done simply destroy the window automatically. The catch is I can't tell how much time will the command take to execute. So I can't really use the time module. I tried `subprocess.Popen` but for a specific command (`ffmpeg`) my code just waits until the command is executed when it shouldn't be waitig. For other commands it doesn't have that proble and I can't figure out why. :(
