### ISSUE TITLE
chcp command not working

### ISSUE THREAD

**Issue by NotSoNymos** [Saadmairaj/tkterminal#5]
I'v got widows with ru lang and terminal cant encode it with utf-8 so I decided to change lang of terminal with chcp command but its not working.

![Скриншот 26-03-2022 150129](https://user-images.githubusercontent.com/46649391/160238490-04135ed8-47dd-4233-931d-a5d2f8124ade.jpg)

**Comment by Saadmairaj** [comment]
Every terminal line is basically a new subprocess that doesn't keep the previous settings except the `cd` command. Also, this issue is not related to tkterminal package itself, it is related to tcl/tk version bundled with your python. Try python bundled by anaconda.
