### ISSUE TITLE
Python3 command asks for xcode tools

### ISSUE THREAD

**Issue by Moosems** [Saadmairaj/tkterminal#9]
Sometimes when a user uses the command "Python3" it asks for them to download xcode toolchain or it might crash because it wants to get input

**Comment by Saadmairaj** [comment]
The tkterminal is a very limited cmd based on the subprocess. Basically, every command is a new terminal so commands like python3 will not work.

**Comment by Moosems** [comment]
Is there any way to make it work?

**Comment by Moosems** [comment]
In particular, I am fine with the subprocess not taking inputs but it asking for the command line toolchain can be a problem at times
